#!/usr/bin/env bash

set -e

USAGE="usage: slftp SRC_DIR DEST_DIR SERVER_NAME"
[ $# -ne 3 ] && {
    echo $USAGE >&2
    exit 1
}

SRC_DIR=$1
DEST_DIR=$(echo ${2%%/} | tr -s '/')
SERVER_NAME=$3
LFTP_CMD="mirror $SRC_DIR $DEST_DIR/; exit"
SCREEN_NAME=${SRC_DIR##*/}
if ! screen -list | egrep "\<[0-9]+\.$SCREEN_NAME\>" > /dev/null; then
    screen -dmS $SCREEN_NAME
    screen -S $SCREEN_NAME -p 0 -X screen lftp -e "$LFTP_CMD" \
        sftp://$SERVER_NAME
else
    echo "Screen session \"${SCREEN_NAME}\" already exists." >&2
    exit 1
fi
